pipeline {
    agent any

    environment {
        APP_SERVER = '3.86.102.81'
        PEM_PATH   = '/home/ec2-user/.ssh/autoops-key.pem'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/Madhangi07/AutoOps-DevOps-Platform.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t autoops-dashboard:latest ./docker'
            }
        }

        stage('Test') {
            steps {
                echo 'Running basic test...'
                sh 'docker run --rm autoops-dashboard:latest node -e "console.log(\'App OK\')"'
            }
        }

        stage('Deploy to App Server') {
            steps {
                echo 'Deploying to App Server via Ansible...'
                sh '''
                    ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
                    --tags deploy \
                    -e "target=app"
                '''
            }
        }

        stage('Health Check') {
            steps {
                echo 'Checking app is live...'
                sh 'curl -f http://${APP_SERVER}:80 || echo "Health check failed"'
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfully! AutoOps is live.'
        }
        failure {
            echo 'Pipeline failed. Check logs above.'
        }
    }
}