pipeline {
    agent any

    environment {
        APP_SERVER = '3.86.102.81'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/Madhangi07/AutoOps-DevOps-Platform.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t autoops-dashboard:latest ./docker'
            }
        }

        stage('Test') {
            steps {
                echo 'Running basic test...'
                sh 'docker run --rm autoops-dashboard:latest node -e "console.log(\'App OK\')"'
            }
        }

        stage('Deploy to App Server') {
            steps {
                echo 'Deploying app to App Server...'
                sh '''
                    ssh -i /var/lib/jenkins/.ssh/autoops-key.pem \
                    -o StrictHostKeyChecking=no \
                    ec2-user@3.86.102.81 \
                    "docker stop autoops-dashboard || true && \
                     docker rm autoops-dashboard || true && \
                     docker run -d --name autoops-dashboard \
                     --restart always -p 80:3001 autoops-dashboard:latest"
                '''
            }
        }

        stage('Health Check') {
            steps {
                echo 'Checking app is live...'
                sh 'curl -f http://3.86.102.81:80 || echo "Health check failed"'
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed! AutoOps is live.'
        }
        failure {
            echo 'Pipeline failed. Check logs above.'
        }
    }
}